### YASHASVI VERMA

### Salary prediction from Random numbers using linear regression


Taking 500 random values between 1 and 50 and making prediction of salary based on the number of skills a person has

In [1]:
import numpy as np
import pandas as pd

In [2]:
skills = np.linspace(1, 50, 500, dtype='int')

In [3]:
print(skills)

[ 1  1  1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  2  3  3  3
  3  3  3  3  3  3  3  4  4  4  4  4  4  4  4  4  4  5  5  5  5  5  5  5
  5  5  5  6  6  6  6  6  6  6  6  6  6  6  7  7  7  7  7  7  7  7  7  7
  8  8  8  8  8  8  8  8  8  8  9  9  9  9  9  9  9  9  9  9 10 10 10 10
 10 10 10 10 10 10 11 11 11 11 11 11 11 11 11 11 11 12 12 12 12 12 12 12
 12 12 12 13 13 13 13 13 13 13 13 13 13 14 14 14 14 14 14 14 14 14 14 15
 15 15 15 15 15 15 15 15 15 16 16 16 16 16 16 16 16 16 16 17 17 17 17 17
 17 17 17 17 17 17 18 18 18 18 18 18 18 18 18 18 19 19 19 19 19 19 19 19
 19 19 20 20 20 20 20 20 20 20 20 20 21 21 21 21 21 21 21 21 21 21 22 22
 22 22 22 22 22 22 22 22 22 23 23 23 23 23 23 23 23 23 23 24 24 24 24 24
 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26 26 26
 26 27 27 27 27 27 27 27 27 27 27 28 28 28 28 28 28 28 28 28 28 28 29 29
 29 29 29 29 29 29 29 29 30 30 30 30 30 30 30 30 30 30 31 31 31 31 31 31
 31 31 31 31 32 32 32 32 32 32 32 32 32 32 33 33 33

In [4]:
salaries = skills* 8000

In [5]:
buffer = np.random.randint(1,40000,500)

In [6]:
buffer

array([29752,  1603, 19104,  7524,  4271, 35331,    81, 25741, 36734,
       12279, 17429, 12464, 39297, 31226, 34545, 15385, 23270, 14691,
       17802,  6378,  4258, 21686, 23011, 20580, 12920, 18852, 13135,
       21355, 32605, 36522, 32247, 23258, 36814, 38534,  1400, 30387,
       17965, 23698,  2161, 35634, 17518,    19, 30569,  3727, 33257,
       13671,  6687, 27968,  2875, 18506,  6055, 27969, 31643, 21460,
       28303, 16307, 17178, 12955, 12209, 29537, 36596, 23818, 26497,
       16617, 24776, 21655,  7111,  9777, 14458, 26610,  6206, 27753,
       33872, 17232, 32291,  5161, 24795, 32623, 15597, 19145,  7497,
       35872,  3545, 36033, 28584,  8118, 39433,  1270, 14489,  4502,
       16411, 13118, 34342, 36038, 16290,   478, 14050, 21195, 15521,
       21254, 30693,  4244, 20451, 16504, 10137,  5881, 17622, 19052,
       37379, 34885,   562, 24729, 17517, 26296, 17572, 29729,  6135,
       11131, 12960,  4599, 29793, 26346, 22664, 39574, 21261,  3541,
       35146, 14016,

In [7]:
salaries = (skills* 8000)+buffer

In [8]:
salaries

array([ 37752,   9603,  27104,  15524,  12271,  43331,   8081,  33741,
        44734,  20279,  25429,  28464,  55297,  47226,  50545,  31385,
        39270,  30691,  33802,  22378,  20258,  45686,  47011,  44580,
        36920,  42852,  37135,  45355,  56605,  60522,  56247,  55258,
        68814,  70534,  33400,  62387,  49965,  55698,  34161,  67634,
        49518,  40019,  70569,  43727,  73257,  53671,  46687,  67968,
        42875,  58506,  46055,  75969,  79643,  69460,  76303,  64307,
        65178,  60955,  60209,  77537,  84596,  71818,  82497,  72617,
        80776,  77655,  63111,  65777,  70458,  82610,  62206,  83753,
        97872,  81232,  96291,  69161,  88795,  96623,  79597,  83145,
        71497,  99872,  75545, 108033, 100584,  80118, 111433,  73270,
        86489,  76502,  88411,  85118, 114342, 116038,  96290,  80478,
        94050, 101195,  95521, 101254, 110693,  84244, 108451, 104504,
        98137,  93881, 105622, 107052, 125379, 122885,  88562, 112729,
      

In [9]:
df = pd.DataFrame({
    "Skills": skills, 
    "Salaries":salaries})

In [10]:
df

Skills  Salaries
0         1     37752
1         1      9603
2         1     27104
3         1     15524
4         1     12271
..      ...       ...
495      49    424059
496      49    424793
497      49    413233
498      49    430176
499      50    431513

[500 rows x 2 columns]

In [11]:
import sklearn

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X=df[["Skills"]].values
Y=df[["Salaries"]].values

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, train_size= 0.8)

In [15]:
X_train.shape

(400, 1)

In [16]:
Y

array([[ 37752],
       [  9603],
       [ 27104],
       [ 15524],
       [ 12271],
       [ 43331],
       [  8081],
       [ 33741],
       [ 44734],
       [ 20279],
       [ 25429],
       [ 28464],
       [ 55297],
       [ 47226],
       [ 50545],
       [ 31385],
       [ 39270],
       [ 30691],
       [ 33802],
       [ 22378],
       [ 20258],
       [ 45686],
       [ 47011],
       [ 44580],
       [ 36920],
       [ 42852],
       [ 37135],
       [ 45355],
       [ 56605],
       [ 60522],
       [ 56247],
       [ 55258],
       [ 68814],
       [ 70534],
       [ 33400],
       [ 62387],
       [ 49965],
       [ 55698],
       [ 34161],
       [ 67634],
       [ 49518],
       [ 40019],
       [ 70569],
       [ 43727],
       [ 73257],
       [ 53671],
       [ 46687],
       [ 67968],
       [ 42875],
       [ 58506],
       [ 46055],
       [ 75969],
       [ 79643],
       [ 69460],
       [ 76303],
       [ 64307],
       [ 65178],
       [ 60955],
       [ 60209

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
linReg = LinearRegression()

In [19]:
linReg.fit(X_train, Y_train)

LinearRegression()

In [20]:
linReg.intercept_

array([19529.47980168])

In [22]:
usk=int(input("Enter number of skills and i will help you predict your salary"))
print("Your predicted salary is :" ,linReg.predict([[usk]])[0][0])

Enter number of skills and i will help you predict your salary1
Your predicted salary is : 27584.66451905188
